global:
  extensions:
    extAuth:
      extauthzServerRef:
        name: oathkeeper-oathkeeper-api-4456
        namespace: gloo-system
      requestTimeout: 0.5s
      httpService:
        pathPrefix: /decisions
        response:
          allowedUpstreamHeaders:
            - x-user-id

gateway:
  validation:
    alwaysAcceptResources: false
    allowWarnings: false

gatewayProxies:
  gatewayProxy:
    gatewaySettings:
      disableHttpsGateway: true

gloo:
  deployment:
    disableUsageStatistics: true

settings:
  create: true
  disableKubernetesDestinations: true
  invalidConfigPolicy:
    replaceInvalidRoutes: true
    invalidRouteResponseCode: 502
  writeNamespace: gloo-system
  watchNamespaces:
  - default
  - gloo-system
  - oathkeeper
